# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeApplication' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeApplication

  # target 'ReactNativeApplication-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'ReactNativeApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeApplication-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeApplication-tvOS

  target 'ReactNativeApplication-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
